### ISSUE TITLE
Specific version of pytorch and torch_geometric 

### ISSUE THREAD

**Issue by bokveizen** [Thinklab-SJTU/One-Shot-Cardinality-NN-Solver#1]
Dear authors,
Thank you for your wonderful work!
May I ask whether there are specific version requirements on pytorch and torch_geometric?
Thanks!

**Comment by rogerwwww** [comment]
Hi there, 

Many thanks for your interest in our work!

The PyTorch and PyG versions we used are:
```
torch                        1.6.0+cu101
torch-cluster                1.5.9
torch-geometric              1.6.3
torch-scatter                2.0.6
torch-sparse                 0.6.9
torch-spline-conv            1.2.1
```
and I think any newer versions will work too.

**Comment by bokveizen** [comment]
Thanks a lot! BTW, the package easydict is required but not listed in the readme!

**Comment by rogerwwww** [comment]
Thanks. Will update the readme.
