### ISSUE TITLE
train_gumbel_sample_num missing in max_cover_twitch.yaml

### ISSUE THREAD

**Issue by bokveizen** [Thinklab-SJTU/One-Shot-Cardinality-NN-Solver#3]
Dear authors,
Seemingly the parameter "train_gumbel_sample_num" is missing in "max_cover_twitch.yaml".
Is it "train_gumbel_sample_num = 10" as in the other two yaml files for max covering?

**Comment by rogerwwww** [comment]
Hi there,

According to our experiment setting (as stated in our paper), the model is not trained on twitch dataset. That's why there is no ``train_gumbel_sample_num`` in twitch's yaml file.

**Comment by rogerwwww** [comment]
Our script should load the pretrained model from ``max_cover_rand500.yaml`` -- but if rand500 is not run, there seems to be an issue. I will update ``train_gumbel_sample_num = 10`` based on your suggestions.

**Comment by bokveizen** [comment]
I see! Thanks a lot for your reply!
