### ISSUE TITLE
On some "additional" topk baseline methods in the code

### ISSUE THREAD

**Issue by bokveizen** [Thinklab-SJTU/One-Shot-Cardinality-NN-Solver#4]
Dear authors,
Really sorry for disturbing you again!
As I can see in the configuration files, only for the experiment on the max covering problem with random graphs of size 500, the 'perturb-topk', 'blackbox-topk', and the 'lml-topk' methods are used.
Is there any specific reason for that?
Thanks!

**Comment by rogerwwww** [comment]
No worries. They are intended to reproduce the ablation study (Table 2 in our main paper).

**Comment by bokveizen** [comment]
Thanks a lot!
