### ISSUE TITLE
Possible solution for Maximum Clique

### ISSUE THREAD

**Issue by Pamphlett** [Thinklab-SJTU/One-Shot-Cardinality-NN-Solver#5]
Hi Runzhong,

Really appreciated your great work!
I'm wondering if it's possible to have a NN solver for the maximum clique problem?
Could you share some insights on this?

**Comment by rogerwwww** [comment]
Hi Pengyu,

You raised a very interesting point. You can take a look at our recent ICML'23 paper (https://github.com/Thinklab-SJTU/LinSATNet). If you replace the Sinkhorn layer in this repo with LinSATLayer, it might work.

**Comment by Pamphlett** [comment]
Thanks for the reference. I'll go and have a try!
