### ISSUE TITLE
Euclidean Squared Distance is used instead of Euclidean Distance

### ISSUE THREAD

**Issue by bokveizen** [Thinklab-SJTU/One-Shot-Cardinality-NN-Solver#8]
In `src/facility_location_methods.py`, the `_pairwise_euclidean` function seemingly computes Euclidean Squared Distance instead of Euclidean Distance, since the square root is not taken.

**Comment by rogerwwww** [comment]
Thank you so much for your careful reading and the correction 🤗🤗

**Comment by bokveizen** [comment]
You are welcome! Since the non-sqrt version is also a distance metric (see, e.g, http://www.improvedoutcomes.com/docs/WebSiteDocs/Clustering/Clustering_Parameters/Euclidean_and_Euclidean_Squared_Distance_Metrics.htm), I think overall it is still fine. Maybe you can mention this in the readme so that in the future other researchers using this work are aware of this.

**Comment by rogerwwww** [comment]
Nice suggestion! Done.
